# Generated by Django 5.2.5 on 2025-09-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
