# Generated by Django 5.2.5 on 2025-09-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_delete_customuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": (
                    ("can_view", "Can view book"),
                    ("can_create", "Can create book"),
                    ("can_edit", "Can edit book"),
                    ("can_delete", "Can delete book"),
                )
            },
        ),
    ]
